# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable the `avoid_print` rule, which suggests avoiding the use of `print`.
    avoid_print: false

    # Disable the `unused_import` rule, which suggests removing unused imports.
    unused_import: false

    # Enable the `prefer_single_quotes` rule, which suggests using single quotes for strings.
    prefer_single_quotes: true

    # Add any other rules you want to customize here.
    # For example, if you want to ignore the `prefer_const_constructors` rule:
    # prefer_const_constructors: false

    # You can find more rules and their descriptions here: https://dart.dev/lints
